### ISSUE TITLE
Add support for prefixes

### ISSUE THREAD

**Issue by ArvindSinghRawat** [ArvindSinghRawat/Git-Automatic-Semver-Tagging#4]
# Introduction

Currently, this action only supports versioning in the very strict format `%d.%d.%d`. Ideally, SemVer supports prefixes like `v` for version, and suffixes for dev releases like `-alpha`, `-beta`, etc.

# The idea is to support static or dynamic prefixes and suffixes
- **Static**: Should be configurable in workflow definition as an input. Like
  ```yml
  - uses: ArvindSinghRawat/Automatic-Semantic-versioning-semver-Tagging@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION_PREFIX" ${{ github.events.inputs.version_prefix || 'v' }}
        VERSION_SUFFIX" ${{ github.events.inputs.version_prefix || '' }}=
  ```
- **Dynamic**: Should be able to use commit message to figure out, similar to patch version.
